apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <LOCAL_SC>
  labels:
    release: openldap
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
