apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-data
  labels:
    release: openldap
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: <MAX_SIZE>
  local:
    path: <PATH>/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <WORKER_NODE>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: <SC_NAME>
  volumeMode : Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-config
  labels:
    release: openldap
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: <PATH>/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <WORKER_NODE>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: <SC_NAME>
  volumeMode : Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-certs
  labels:
    release: openldap
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: <PATH>/certs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <WORKER_NODE>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: <SC_NAME>
  volumeMode : Filesystem